export { default as BithumbLogoSVG } from "./BithumbLogoSVG.svg";
export { default as BuyUCoinLogoSVG } from "./BuyUCoinLogoSVG.svg";
export { default as CoinbaseLogoSVG } from "./CoinbaseLogoSVG.svg";
export { default as HuboiLogoSVG } from "./HuboiLogoSVG.svg";
export { default as KucoinLogoSVG } from "./KucoinLogoSVG.svg";
export { default as OKXLogoSVG } from "./OKXLogoSVG.svg";
export { default as BinanceExchangeLogoSVG } from "./BinanceExchangeLogoSVG.svg";
export { default as QuickSwapLogoSVG } from "./QuickSwapLogoSVG.svg";
export { default as QuickSwapLogoJPG } from "./QuickSwapLogoJPG.jpeg";
